# Site settings
encoding: UTF-8
title: "Computer Vision Drone"
email: info@codecentric.de
description: 
baseurl: "/drone-test-2"
url: "https://alenaul.github.io/drone-test-2"
title_description: "Building an interactive computer vision drone."
title_image: header3.png
google_analytics:
disqus_account: 
github_repository: https://alenaul.github.io/drone-test-2
addthis_id: ra-513c6fa83da6ec67
post_limit: 3
collections:
  posts:
    output: true
    permalink: ./:title:output_ext
    scope:
      path: ""
      type: posts
    values:
    layout: page
collections:
   opencv-python-examples:
    output: true
    permalink: ./:title:output_ext
    scope:
      path: ""
      type: opencv-python-examples
    values:
    layout: page

# Social usernames/URLs
twitter_username: 
github_username:  codecentric
instagram_username: 
reddit_username: 
linkedin_link: 
google_plus_link:
stackoverflow_link: 
xing_link:
facebook_link:

# Footer
footer_left: "<a href=\"https://www.codecentric.de\">Impressum</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/codecentric/computer-vision-drone\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
